### ISSUE TITLE
Homey Pro SDK3

### ISSUE THREAD

**Issue by martijnchel** [rkokkelk/com.jreenen.homeyharmonyhub#108] opened 2022-10-14 21:07 UTC
Since this is one of my favorite apps. Are you planning to support the new SDK for Homey Pro? Would be great of course. And if not, right now the probability is there that older apps will be removed, which would be a real shame. 

Thanks!

**Comment by pjmpessers** [comment] 2023-01-02 14:47
Great to see that you are supporting and working on SDKv3, @rkokkelk . I sideloaded it, but for me it seems to be crashing on my homey pro early 2019. Is this bug known by you?

In the mean time, thanks.

**Comment by pjmpessers** [comment] 2023-02-25 11:33
Hello @rkokkelk .
I sideloaded the master brach, and it works for me. But i don't see a change in the version number. It is still V2.0.9.
Is this now HP2023 compatible?

Thanks for supporting and developing this app.

**Comment by rkokkelk** [comment] 2023-02-25 13:09
No the changes on the master branch is some initial work to clean up the code. The active development will be done in the `sdkv3` branch and is currently not stable. Once I'm ready to release an alpha version I'll let you guys know.

**Comment by Wvanoors** [comment] 2023-02-25 15:06
Thanks a lot for updating the app! @rkokkelk.

**Comment by rkokkelk** [comment] 2023-02-25 21:21
A test release has been published. Please feel free to test and provide feedback. 

* https://homey.app/a/com.jreenen.homeyharmonyhub/test/

**Comment by pjmpessers** [comment] 2023-02-25 21:33
Hello Roy.

I updated the test version. And this one doesn't crash. It seems that devices works.
But when i want to use a activity it is saying "could not get device by id" 

If i go to devices and then install harmony and choose activities then i see them all. So it seems he doen't look at the old device id for activities and want to make new ones.

But then many flows will be broken.

**Comment by rkokkelk** [comment] 2023-02-25 21:56
Yeah this update should definitely not result in the requirement of adding the Hub again, thus destroying all existing flows. I've not encountered this is issue on my own installation, but will look into it.

**Comment by pjmpessers** [comment] 2023-02-25 22:27
Thank you Roy. If i'm sure that all the faults are gone and it is HP2023 compatible i don't mind te rebuild my flows. But only if i'm sure the little faults and errors are gone. I'm already excited and hopeful that my harmony is still usable on HP2023.

**Comment by caseda** [comment] 2023-02-26 11:57
I've just installed v3 as well, on an older Homey Pro (2019) and Homey Pro (2023) but have also the "invalid device id" for activities, this is for both Homeys, where the older Homey has exisitng devices and activities, but the new Homey Pro is (of course) fully new devices.

**Comment by rkokkelk** [comment] 2023-02-26 12:54
I've identified the issue and should not be fixed. It has been fixed by f1c0639. Please us the test link to reinstall the app with the latest version.

**Comment by caseda** [comment] 2023-02-26 13:00
Confirmed working with v3.0.1 on both Homeys

**Comment by pjmpessers** [comment] 2023-02-26 14:22
This is great. It is also almost working flawless. Only one small thing.
1. First of all....On my HP2019 it now sees my devices and my activities. So happy with that.
2. When you place a few commands in a short periode (Like volume up/down) the app can't keep up. Like the commands get in a queue. After a while i get the message time out after 30000ms. But after a while a command will still be executed. So it knows what to do, but takes some time for it.

For everything elso, happy that this will also be useble on the HP2023.

**Comment by Wvanoors** [comment] 2023-02-27 14:56
Bit off-topic maybe (sorry) but does somone her knows if Homey reproduces the ir-signals?
And would it be possibel to use a bridge as repeater in a different room with he same one Harmony Hub? 
I am planning to get me a used hub soon.....

**Comment by rkokkelk** [comment] 2023-02-28 20:01
With the official release of the latest version which set SDK version 3, I define this issue resolved.

**Closed by rkokkelk** 2023-02-28 20:01 UTC
Labels: enhancement, short term, fixed_in_upcoming_release
